CheAlex\ImageStorage\Domain\Model\Image:
    type: entity
    table: images
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fileName:
            type: string
            length: 255
            unique: true
        isActive:
            type: boolean
        createdAt:
            type: datetime_immutable
